"""initial: 9 core entities

Revision ID: 9e70747e5efa
Revises: 
Create Date: 2026-08-01 16:46:07.807658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e70747e5efa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名，全局唯一'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密密码（bcrypt）'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：admin / teacher / student / parent'),
    sa.Column('role_id', sa.String(length=36), nullable=False, comment='对应角色实体的 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('parents',
    sa.Column('name', sa.String(length=100), nullable=False, comment='家长姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False, comment='学校名称'),
    sa.Column('region', sa.String(length=100), nullable=False, comment='所在地区'),
    sa.Column('address', sa.Text(), nullable=False, comment='详细地址'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('current_semester', sa.String(length=50), nullable=False, comment='当前学期，如 2025-2026 第一学期'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('name', sa.String(length=50), nullable=False, comment='年级名称，如 高一'),
    sa.Column('academic_year', sa.Integer(), nullable=False, comment='学年'),
    sa.Column('school_id', sa.String(length=36), nullable=False, comment='所属学校 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='教师姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='账号状态：pending / approved / rejected'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：admin / teacher'),
    sa.Column('school_id', sa.String(length=36), nullable=False, comment='所属学校 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('name', sa.String(length=100), nullable=False, comment='班级名称，如 高一(3)班'),
    sa.Column('student_count', sa.Integer(), nullable=False, comment='当前学生人数'),
    sa.Column('stage', sa.String(length=20), nullable=False, comment='学段：高中 / 初中'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科'),
    sa.Column('grade_id', sa.String(length=36), nullable=False, comment='所属年级 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('name', sa.String(length=100), nullable=False, comment='学生姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending / approved / rejected'),
    sa.Column('barrier_concept_rate', sa.Float(), nullable=False, comment='概念理解型障碍占比'),
    sa.Column('barrier_reading_rate', sa.Float(), nullable=False, comment='审题障碍型占比'),
    sa.Column('barrier_expression_rate', sa.Float(), nullable=False, comment='表述障碍型占比'),
    sa.Column('barrier_updated_at', sa.DateTime(), nullable=True, comment='障碍画像最后更新时间'),
    sa.Column('total_practice_count', sa.Integer(), nullable=False, comment='累计完成练习数'),
    sa.Column('last_practice_at', sa.DateTime(), nullable=True, comment='最近练习时间'),
    sa.Column('bind_code', sa.String(length=6), nullable=False, comment='6 位家长绑定码'),
    sa.Column('class_id', sa.String(length=36), nullable=True, comment='所属班级 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_class_subjects',
    sa.Column('subject', sa.String(length=50), nullable=False, comment='任教学科'),
    sa.Column('is_homeroom', sa.Boolean(), nullable=False, comment='是否为班主任'),
    sa.Column('teacher_id', sa.String(length=36), nullable=False, comment='教师 ID'),
    sa.Column('class_id', sa.String(length=36), nullable=False, comment='班级 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_parent_bindings',
    sa.Column('bind_code', sa.String(length=6), nullable=False, comment='绑定时使用的绑定码'),
    sa.Column('relation_type', sa.String(length=20), nullable=False, comment='关系：father / mother / guardian'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='绑定状态：active / inactive'),
    sa.Column('student_id', sa.String(length=36), nullable=False, comment='学生 ID'),
    sa.Column('parent_id', sa.String(length=36), nullable=False, comment='家长 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_parent_bindings')
    op.drop_table('teacher_class_subjects')
    op.drop_table('students')
    op.drop_table('classes')
    op.drop_table('teachers')
    op.drop_table('grades')
    op.drop_table('schools')
    op.drop_table('parents')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
