"""add_diagnosis_engine_models

Revision ID: a7c3d9e1f2b4
Revises: cec35d6bfdef
Create Date: 2026-08-13 12:30:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c3d9e1f2b4'
down_revision: Union[str, None] = 'cec35d6bfdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_records',
    sa.Column('exam_id', sa.String(length=36), nullable=False, comment='关联试卷定义 ID'),
    sa.Column('class_id', sa.String(length=36), nullable=False, comment='班级 ID'),
    sa.Column('taken_at', sa.DateTime(), nullable=False, comment='考试时间'),
    sa.Column('avg_score', sa.Float(), nullable=True, comment='平均分'),
    sa.Column('reference_count', sa.Integer(), nullable=True, comment='参考人数'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barrier_configs',
    sa.Column('teacher_id', sa.String(length=36), nullable=False, comment='教师 ID'),
    sa.Column('concept_threshold', sa.Integer(), nullable=False, comment='概念理解型连续错误触发阈值'),
    sa.Column('reading_threshold', sa.Integer(), nullable=False, comment='审题障碍型连续错误触发阈值'),
    sa.Column('expression_threshold', sa.Integer(), nullable=False, comment='表述障碍型连续错误触发阈值'),
    sa.Column('mastery_threshold', sa.Integer(), nullable=False, comment='掌握判定连续正确阈值'),
    sa.Column('auto_sync_to_student', sa.Boolean(), nullable=False, comment='诊断结论是否自动同步学生端'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('diagnosis_overrides',
    sa.Column('student_id', sa.String(length=36), nullable=False, comment='学生 ID'),
    sa.Column('teacher_id', sa.String(length=36), nullable=False, comment='操作教师 ID'),
    sa.Column('old_barrier', sa.JSON(), nullable=False, comment='覆盖前画像 {"concept": x, "reading": y, "expression": z}'),
    sa.Column('new_barrier', sa.JSON(), nullable=False, comment='覆盖后画像 {"concept": x, "reading": y, "expression": z}'),
    sa.Column('reason', sa.Text(), nullable=False, comment='覆盖原因'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answers',
    sa.Column('exam_record_id', sa.String(length=36), nullable=False, comment='考试记录 ID'),
    sa.Column('student_id', sa.String(length=36), nullable=False, comment='学生 ID'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='题目 ID'),
    sa.Column('student_answer', sa.Text(), nullable=False, comment='学生作答内容'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否正确'),
    sa.Column('barrier_type', sa.Enum('CONCEPT', 'READING', 'EXPRESSION', name='barriertype'), nullable=True, comment='障碍类型判定（未诊断时为 NULL）'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='判定置信度（0.0-1.0）'),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False, comment='连续错误次数'),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False, comment='连续正确次数'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['exam_record_id'], ['exam_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_answers')
    op.drop_table('diagnosis_overrides')
    op.drop_table('barrier_configs')
    op.drop_table('exam_records')
    # ### end Alembic commands ###
