"""add_question_audit_knowledge_models

Revision ID: cd1b606495f6
Revises: 9e70747e5efa
Create Date: 2026-08-10 15:13:50.936039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1b606495f6'
down_revision: Union[str, None] = '9e70747e5efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_exams',
    sa.Column('source', sa.String(length=200), nullable=False, comment="试卷来源（如'全国卷I'、'湖南卷'、'北京模拟卷'）"),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('question_number', sa.String(length=20), nullable=True, comment="题号（如 '7', '26(1)'）"),
    sa.Column('knowledge_points', sa.JSON(), nullable=True, comment='知识点标签 JSON 数组'),
    sa.Column('difficulty', sa.String(length=20), nullable=True, comment='难度等级'),
    sa.Column('discrimination', sa.Float(), nullable=True, comment='区分度（统计指标，衡量题目区分优生和差生的能力）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_points',
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识点名称（全局唯一）'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="所属分类（如'电解质溶液'、'有机化学'）"),
    sa.Column('pubchem_id', sa.String(length=50), nullable=True, comment='关联的 PubChem 化合物编号'),
    sa.Column('question_count', sa.Integer(), nullable=False, comment='关联题目数量（缓存计数）'),
    sa.Column('error_rate', sa.Float(), nullable=False, comment='动态错误率（缓存计算值: 错误次数/作答次数）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_name'), ['name'], unique=True)

    op.create_table('question_sets',
    sa.Column('name', sa.String(length=200), nullable=False, comment='题目集名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='题目集描述'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者教师 ID'),
    sa.Column('school_id', sa.String(length=36), nullable=False, comment='所属学校 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('type', sa.Enum('CHOICE', 'FILL', 'CALC', 'EXPERIMENT', 'INFERENCE', name='questiontype'), nullable=False, comment='题目类型：choice/fill/calc/experiment/inference'),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'COMPETITION', name='difficulty'), nullable=False, comment='难度等级：easy/medium/hard/competition'),
    sa.Column('content_i18n', sa.JSON(), nullable=False, comment='多语言题目正文，格式: {"zh": "...", "en": "..."}'),
    sa.Column('options_i18n', sa.JSON(), nullable=True, comment='多语言选项，格式: {"zh": ["A...", "B..."], "en": [...]}'),
    sa.Column('answer_i18n', sa.JSON(), nullable=False, comment='多语言答案，格式: {"zh": "...", "en": "..."}'),
    sa.Column('analysis_i18n', sa.JSON(), nullable=True, comment='多语言题目解析，格式: {"zh": "...", "en": "..."}'),
    sa.Column('images', sa.JSON(), nullable=True, comment='图片引用: [{"url": "...", "alt": "...", "position": "content"}]'),
    sa.Column('knowledge_points', sa.JSON(), nullable=False, comment='知识点标签: ["盐类水解", "电解质溶液"]'),
    sa.Column('source', sa.Enum('AI_GENERATED', 'MANUAL', 'DAILY_PRACTICE', 'OCR_IMPORT', name='questionsource'), nullable=False, comment='题目来源：ai_generated/manual/daily_practice/ocr_import'),
    sa.Column('audit_status', sa.Enum('PENDING', 'AUDITING', 'PASSED', 'WARNING', 'BLOCKED', name='auditstatus'), nullable=False, comment='审核状态：pending/auditing/passed/warning/blocked'),
    sa.Column('audit_report', sa.JSON(), nullable=True, comment='四维审核报告 JSON 快照'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者教师 ID'),
    sa.Column('historical_exam_id', sa.String(length=36), nullable=True, comment='关联真题 ID（变体生成时）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['historical_exam_id'], ['historical_exams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_set_items',
    sa.Column('question_set_id', sa.String(length=36), nullable=False, comment='题目集 ID'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='题目 ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_set_items')
    op.drop_table('questions')
    op.drop_table('question_sets')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_name'))

    op.drop_table('knowledge_points')
    op.drop_table('historical_exams')
    # ### end Alembic commands ###
