"""add_exams_and_exam_question_sets

Revision ID: cec35d6bfdef
Revises: cd1b606495f6
Create Date: 2026-08-10 17:46:14.213720
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec35d6bfdef'
down_revision: Union[str, None] = 'cd1b606495f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('name', sa.String(length=200), nullable=False, comment='考试名称'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ENDED', 'CANCELLED', name='examstatus'), nullable=False, comment='考试状态：draft/active/ended/cancelled'),
    sa.Column('classes', sa.JSON(), nullable=False, comment='参与班级列表，格式: [{"id": "cls-001", "name": "高三(1)班"}]'),
    sa.Column('total_score', sa.Integer(), nullable=False, comment='试卷总分'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='考试时长（分钟）'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者教师 ID'),
    sa.Column('school_id', sa.String(length=36), nullable=False, comment='所属学校 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_question_sets',
    sa.Column('exam_id', sa.String(length=36), nullable=False, comment='考试 ID'),
    sa.Column('question_set_id', sa.String(length=36), nullable=False, comment='题库文件夹 ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discrimination', sa.Float(), nullable=True, comment='区分度（统计指标，衡量题目区分优生和差生的能力）'))
        batch_op.drop_column('Float')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Float', sa.FLOAT(), nullable=True))
        batch_op.drop_column('discrimination')

    op.drop_table('exam_question_sets')
    op.drop_table('exams')
    # ### end Alembic commands ###
