"""add_practice_and_review_models

Revision ID: f1a2b3c4d5e6
Revises: a7c3d9e1f2b4
Create Date: 2026-08-15 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'a7c3d9e1f2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. exam_records 加列 + exam_id 放宽可空（SQLite 下 batch 重建表）
    with op.batch_alter_table('exam_records') as batch_op:
        batch_op.add_column(
            sa.Column('type', sa.Enum('EXAM', 'PRACTICE', name='recordtype'),
                      nullable=False, server_default='EXAM', comment='记录类型：exam / practice')
        )
        batch_op.add_column(
            sa.Column('student_id', sa.String(length=36), nullable=True,
                      comment='学生 ID（练习记录时填）')
        )
        batch_op.create_foreign_key(
            'fk_exam_records_student_id', 'students', ['student_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.alter_column('exam_id', existing_type=sa.String(length=36), nullable=True)

    # 2. review_tasks 新表
    op.create_table('review_tasks',
        sa.Column('student_id', sa.String(length=36), nullable=False, comment='所属学生 ID'),
        sa.Column('question_id', sa.String(length=36), nullable=False, comment='关联题目 ID'),
        sa.Column('review_level', sa.Integer(), nullable=False, comment='复习级别 0-5（5 级已掌握）'),
        sa.Column('status', sa.Enum('PENDING', 'DONE', name='reviewstatus'), nullable=False, comment='状态：pending / done'),
        sa.Column('first_learned_at', sa.DateTime(), nullable=False, comment='首次学习时间'),
        sa.Column('next_review_at', sa.DateTime(), nullable=True, comment='下次复习时间（已掌握时清空）'),
        sa.Column('last_completed_at', sa.DateTime(), nullable=True, comment='最近完成/掌握时间'),
        sa.Column('consecutive_correct', sa.Integer(), nullable=False, comment='连续答对次数'),
        sa.Column('consecutive_errors', sa.Integer(), nullable=False, comment='连续答错次数'),
        sa.Column('review_history', sa.JSON(), nullable=False, comment='每次复习的 {time, correct, level_before, level_after}'),
        sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 主键'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'question_id', name='uq_review_task_student_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_tasks')
    with op.batch_alter_table('exam_records') as batch_op:
        batch_op.drop_constraint('fk_exam_records_student_id', type_='foreignkey')
        batch_op.drop_column('student_id')
        batch_op.drop_column('type')
        batch_op.alter_column('exam_id', existing_type=sa.String(length=36), nullable=False)
    # ### end Alembic commands ###
